on:
  workflow_call:
    inputs:
      jellyfin_version:
        required: true
        type: string
      server_url:
        required: true
        type: string

jobs:
  publish:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clone UX Repository
        uses: actions/checkout@v3
        with:
          repository: jellyfin/jellyfin-ux
          path: .\jellyfin-ux

      - name: Setup Jellyfin server
        run: |
          Invoke-WebRequest '${{ inputs.server_url }}' -OutFile 'jellyfin.zip'
          Expand-Archive 'jellyfin.zip'
          Copy-Item ".\Support Files\LICENSE" -Destination $(Resolve-Path .\jellyfin\jellyfin_*)

      - name: Publish Tray
        run: dotnet publish -c Release -r win-x64 --no-self-contained --output $(Resolve-Path .\jellyfin\jellyfin_*)

      - name: Build installer
        run: |
          $env:InstallLocation = $(Resolve-Path .\jellyfin\jellyfin_*)
          makensis /Dx64 /DUXPATH=$(Resolve-Path .\jellyfin-ux) $(Join-Path -Path $(Resolve-Path .\nsis) -ChildPath jellyfin.nsi)

      - name: Rename Installer
        run: |
          cd .\nsis
          Rename-Item -Path .\jellyfin_*_windows-x64.exe -NewName ("jellyfin_${{ inputs.jellyfin_version }}_windows-x64.exe")

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-x64
          retention-days: 30
          if-no-files-found: error
          path: .\nsis\jellyfin_*_windows-x64.exe

      - name: Upload to GitHub Release
        if: ${{ github.event_name == 'release' }}
        uses: shogo82148/actions-upload-release-asset@v1.5.0
        with:
          upload_url: ${{ github.event.release.upload_url }}
          overwrite: true
          asset_path: .\nsis\jellyfin_*_windows-x64.exe
